### ISSUE TITLE
Problems in Tesla-Menu 1.0.2.

### ISSUE THREAD

**Issue by MythraUwU** [diwo/TextReaderOverlay-NX#1]
Sorry for the inconvenience, TextReaderOverlay-NX works correctly, but in version 1.0.2 of Tesla-Menu it gives problems, the controls seem not to work and is not displayed correctly.

Thank you.

**Comment by diwo** [comment]
Hey, thanks for reaching out. There's now a [version 1.1](https://github.com/diwo/TextReaderOverlay-NX/releases/tag/1.1) of TextReaderOverlay that should fix the compatibility issue with the latest version of tesla. Let me know if this resolves the issue. Thanks!

**Comment by MythraUwU** [comment]
Yes, it works correctly, thanks for your work.

With your permission I close the ISSUE.
